# Generated by Django 2.2.3 on 2019-07-18 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='body',
            new_name='posttext',
        ),
        migrations.RemoveField(
            model_name='post',
            name='title',
        ),
    ]
