# Generated by Django 2.2.3 on 2019-07-21 15:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_auto_20190720_2039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateField(default=datetime.datetime(2019, 7, 21, 18, 20, 2, 563375)),
        ),
    ]
